<footer>
        <a href="https://last-minute-heroes.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?assignee=unassigned&epics=visible&issueParent=10000&atlOrigin=eyJpIjoiY2NlODBiZjEwYzgzNGRjOWE1NzY4M2YxZTZhMTA0ZTIiLCJwIjoiaiJ9">Jira Epic</a>
        <a href="mailto:info@companyname.com.au">Email</a>
        <a href="https://github.com/105699937/Last-Minute-Heroes.git">Github</a>
    </footer>